/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academiagolds;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class cadastroRecep extends javax.swing.JDialog {

    private Connection con;
    boolean Up = false;
    String id = "";

    /**
     * Creates new form NewJFrame
     */
    public cadastroRecep(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo(null);
        JBedit.setVisible(false);
    }

    cadastroRecep(java.awt.Frame parent, boolean modal, String id) {
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo(null);
        this.id = id;
        preencheCampos();
        habilitarCampos(Up);
        Up = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JRBG = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lrg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Lnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Lend = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Lbairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Lcep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Lcpf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Lcidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Lnum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Lctps = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JRBfem = new javax.swing.JRadioButton();
        JRBmasc = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        Lbanco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Lag = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Lnconta = new javax.swing.JTextField();
        JBenvia = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Llogin = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Lsenha = new javax.swing.JTextField();
        JBedit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Cadastro de Recepcionista");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Nome:");

        jLabel2.setText("RG:");

        Lnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnomeActionPerformed(evt);
            }
        });

        jLabel3.setText("End:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("CEP:");

        jLabel7.setText("CPF:");

        jLabel8.setText("Cidade:");

        jLabel9.setText("Nº:");

        jLabel10.setText("CTPS:");

        jLabel11.setText("Sexo:");

        JRBG.add(JRBfem);
        JRBfem.setText("F");
        JRBfem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBfemActionPerformed(evt);
            }
        });

        JRBG.add(JRBmasc);
        JRBmasc.setSelected(true);
        JRBmasc.setText("M");
        JRBmasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBmascActionPerformed(evt);
            }
        });

        jLabel13.setText("Banco:");

        jLabel14.setText("Ag:");

        jLabel15.setText("Nº conta:");

        Lnconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LncontaActionPerformed(evt);
            }
        });

        JBenvia.setText("Enviar");
        JBenvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBenviaActionPerformed(evt);
            }
        });

        jLabel6.setText("Login:");

        jLabel17.setText("Senha:");

        JBedit.setText("Editar Cadastro");
        JBedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(Lcpf))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JRBmasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JRBfem))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lrg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Lend))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lbairro)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lcep, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lnum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lctps, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Lcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Llogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lbanco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(7, 7, 7)
                                .addComponent(Lag, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lnconta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBedit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBenvia)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Lnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JRBfem)
                        .addComponent(JRBmasc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Lrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Lcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Lend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Lbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Lcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Lcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Lnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Lctps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Lbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Lag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Lnconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Llogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(Lsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBenvia)
                    .addComponent(JBedit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnomeActionPerformed

    private void JRBfemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBfemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBfemActionPerformed

    private void JRBmascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBmascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBmascActionPerformed

    private void JBenviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBenviaActionPerformed
        Envia();
    }//GEN-LAST:event_JBenviaActionPerformed

    private void LncontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LncontaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LncontaActionPerformed

    private void JBeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeditActionPerformed
        habilitarCampos(Up);
        JBedit.setEnabled(!Up);
    }//GEN-LAST:event_JBeditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cadastroRecep dialog = new cadastroRecep(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBedit;
    private javax.swing.JButton JBenvia;
    private javax.swing.ButtonGroup JRBG;
    private javax.swing.JRadioButton JRBfem;
    private javax.swing.JRadioButton JRBmasc;
    private javax.swing.JTextField Lag;
    private javax.swing.JTextField Lbairro;
    private javax.swing.JTextField Lbanco;
    private javax.swing.JTextField Lcep;
    private javax.swing.JTextField Lcidade;
    private javax.swing.JTextField Lcpf;
    private javax.swing.JTextField Lctps;
    private javax.swing.JTextField Lend;
    private javax.swing.JTextField Llogin;
    private javax.swing.JTextField Lnconta;
    private javax.swing.JTextField Lnome;
    private javax.swing.JTextField Lnum;
    private javax.swing.JTextField Lrg;
    private javax.swing.JTextField Lsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private void Envia() {
        String requisicao = null;
        String teste = null;
        if (Up) {
            requisicao = "UPDATE recepcionista SET Nome = ?, CPF = ?, RG  = ?, CTPS  = ?, Sexo  = ?, cidade  = ? ,CEP = ?, bairro  = ?, rua  = ?, numero = ?, banco = ?, agencia = ?, num = ?, login = ?, senha = ? WHERE cod = ?";
            teste = "SELECT * from recepcionista WHERE cpf = ? and cod <> ?";
        } else {
            requisicao = "INSERT INTO recepcionista (Nome,CPF,RG,CTPS,Sexo,cidade,CEP,bairro,rua,numero,banco,agencia,num,login,senha) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            teste = "SELECT * from recepcionista WHERE cpf = ? ";
        }
        try {
            con = BancoDeDados.getConexao();
            //cria a string para inserir no banco
            String queryV = teste;

            // Cria o comando
            PreparedStatement verif = con.prepareStatement(queryV);
            verif.setString(1, Lcpf.getText());

            if (Up) {
                verif.setString(2, id);
            }
            ResultSet rs = verif.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Recepcionista ja cadastrado");
            } else {
                //cria a string para inserir no banco
                String query = requisicao;

                // Cria o comando
                PreparedStatement stmt = con.prepareStatement(query);

                //seta os valores inseridos no banco
                stmt.setString(1, Lnome.getText());
                stmt.setString(2, Lcpf.getText());
                stmt.setString(3, Lrg.getText());
                stmt.setString(4, Lctps.getText());

                String aux;
                if (JRBmasc.isSelected()) {
                    aux = "M";
                } else {
                    aux = "F";
                }
                stmt.setString(5, aux);
                stmt.setString(6, Lcidade.getText());
                stmt.setString(7, Lcep.getText());
                stmt.setString(8, Lbairro.getText());
                stmt.setString(9, Lend.getText());
                stmt.setString(10, Lnum.getText());
                stmt.setString(11, Lbanco.getText());
                stmt.setString(12, Lag.getText());
                stmt.setString(13, Lnconta.getText());
                stmt.setString(14, Llogin.getText());
                stmt.setString(15, Lsenha.getText());

                if (Up) {
                    stmt.setString(16, id);
                }

                //executa o comando no banco de dados
                stmt.executeUpdate();

                //fecha os comandos de conexão
                stmt.close();
                this.dispose();
            }
            verif.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Dados(s) Invalidos(s)");
            System.out.println(ex);
        }
    }

    private void habilitarCampos(boolean x) {
        Lnome.setEditable(x);
        Lcpf.setEditable(x);
        Lrg.setEditable(x);
        Lcidade.setEditable(x);
        Lbairro.setEditable(x);
        Lend.setEditable(x);
        Lnum.setEditable(x);
        Lcep.setEditable(x);
        JRBfem.setEnabled(x);
        JRBmasc.setEnabled(x);
        JBenvia.setEnabled(x);
        Lbanco.setEditable(x);
        Lag.setEditable(x);
        Lnconta.setEditable(x);
        Llogin.setEditable(x);
        Lsenha.setEditable(x);
        Lctps.setEditable(x);
    }

    private void preencheCampos() {
        try {
            con = BancoDeDados.getConexao();
            //cria a string para inserir no banco
            String query = "SELECT * FROM recepcionista WHERE cod = ?";

            PreparedStatement cmd;
            cmd = con.prepareStatement(query);
            cmd.setString(1, id);

            ResultSet rs;

            rs = cmd.executeQuery();
            while (rs.next()) {
                Lnome.setText(rs.getString("nome"));
                Lcpf.setText(rs.getString("CPF"));
                Lrg.setText(rs.getString("RG"));
                Lcidade.setText(rs.getString("cidade"));
                Lbairro.setText(rs.getString("bairro"));
                Lend.setText(rs.getString("rua"));
                Lnum.setText(rs.getString("numero"));
                Lcep.setText(rs.getString("cep"));
                Lbanco.setText(rs.getString("cep"));
                Lag.setText(rs.getString("agencia"));
                Lnconta.setText(rs.getString("num"));
                Llogin.setText(rs.getString("login"));
                Lsenha.setText(rs.getString("senha"));
                Lctps.setText(rs.getString("ctps"));
                if (rs.getString("sexo").equals("F")) {
                    JRBfem.setSelected(true);
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro de SQL " + ex.getMessage());
        }
    }
}
